name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: Build (${{ matrix.target }})
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./rust_impl -> target"

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: ./rust_impl

      - name: Package Artifacts
        run: |
          # build dir
          cd rust_impl/target/${{ matrix.target }}/release
          
          # filenames
          PKG_NAME="migreedy-${{ github.ref_name }}-${{ matrix.target }}.tar.gz"
          STABLE_NAME="migreedy-linux-x86_64.tar.gz"

          # create binaries and checksums
          tar -czvf "$PKG_NAME" migreedy
          cp "$PKG_NAME" "$STABLE_NAME"
          sha256sum "$PKG_NAME" > "$PKG_NAME.sha256"
          sha256sum "$STABLE_NAME" > "$STABLE_NAME.sha256"
          
          # create artifacts in root
          mkdir -p "${{ github.workspace }}/artifacts"
          
          # move everything there
          mv "$PKG_NAME" "$PKG_NAME.sha256" "$STABLE_NAME" "$STABLE_NAME.sha256" "${{ github.workspace }}/artifacts/"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
